<?php
date_default_timezone_set('America/Chicago');
$ronmadriz_settings = get_option('ronmadriz_settings');
$site_logo_footer   = get_theme_mod('site_logo_footer');
$address            = get_theme_mod('footer_address');
$phone              = get_theme_mod('footer_phone');
$fax                = get_theme_mod('footer_fax');
$email              = get_theme_mod('footer_email');
$footer_newsletter  = get_theme_mod('footer_newsletter');
echo '<footer class="footer">'.PHP_EOL;
echo '<div class="footer__connect">'.PHP_EOL;
echo '<div class="wrapper">'.PHP_EOL;
echo '<span class="footer__logo">'.$site_logo_footer.'</span>'.PHP_EOL;
echo '<span class="footer__connect--title">'..'</span>'.PHP_EOL;
echo '<ul class="footer__connect--list">';
social_media_footer();
echo '</ul>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</footer>'.PHP_EOL;
wp_footer();
// echo $ronmadriz_settings['ronmadriz_footer_extra'];
echo '</body>'.PHP_EOL;
echo '</html>'.PHP_EOL;