<?php
date_default_timezone_set('America/Chicago');
$ronmadriz_settings = get_option('ronmadriz_settings');
$site_logo_footer   = get_theme_mod('site_logo_footer');
$address            = get_theme_mod('footer_address');
$phone              = get_theme_mod('footer_phone');
$fax                = get_theme_mod('footer_fax');
$email              = get_theme_mod('footer_email');
$footer_newsletter  = get_theme_mod('footer_newsletter');
$privacy_policy     = get_the_privacy_policy_link();
echo '<footer class="footer">'.PHP_EOL;
echo '<div class="footer__connect">'.PHP_EOL;
echo '<div class="wrapper">'.PHP_EOL;
echo '<span class="footer__logo">'.$site_logo_footer.'</span>'.PHP_EOL;
echo '<span class="footer__connect--title">';
_e('Connect:', 'fc_core');
echo '</span>'.PHP_EOL;
echo '<ul class="footer__connect--list">';
social_media_footer();
echo '</ul>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="footer__columns">'.PHP_EOL;
echo '<div class="wrapper">'.PHP_EOL;
echo '<span class="footer__column footer__menu">'.PHP_EOL;
include (get_template_directory().'views/components/navigation/mega-foot.php');
echo '</span>'.PHP_EOL;
echo '<span class="footer__column footer__info">'.PHP_EOL;
echo '</span>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="footer__boiler">'.PHP_EOL;
echo '<div class="wrapper">'.PHP_EOL;
echo '<span class="footer__boiler--menu">'.PHP_EOL;
include (get_template_directory().'views/components/navigation/mega-boiler.php');
echo '</span>'.PHP_EOL;
echo '<span class="footer__boiler--info"><em class="footer__boiler--link footer__boiler--copyright">';
_e('&copy; 2020 ', 'fc_core');
echo get_bloginfo('name').'</em> <em class="footer__boiler--link footer__boiler--rights">';
_e('All Rights Reserved', 'fc_core');
echo '<a href="'.$privacy_policy.'" class="footer__boiler--link footer__boiler--privacy">';
_e('Privacy Policy', 'fc_core');
echo '</a></span>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</footer>'.PHP_EOL;
wp_footer();
// echo $ronmadriz_settings['ronmadriz_footer_extra'];
echo '</body>'.PHP_EOL;
echo '</html>'.PHP_EOL;